#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Build a complete Open-H-4D submission from synthetic DICOM, end to end.

Exercises every step a contributor with a PACS export takes, on data small
enough to run in continuous integration on every pull request:

    synthetic DICOM  ->  index  ->  PHI pre-flight  ->  organize
                     ->  convert (dcm2niix)  ->  verify

Nothing here is downloaded, so it is the example to reach for first when you
want to see the shape of a submission or check that your environment works.

    python examples/synthetic-4d/build_example.py --out /tmp/oh4d-synthetic
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from openh4d.convert_dicom import convert_study
from openh4d.dicom_index import build_plan, summarize
from openh4d.manifest import build_manifest, write_manifest
from openh4d.organize_dicom import organize
from openh4d.phi_scan import scan_dicom_source
from openh4d.synthetic_dicom import write_multi_patient_source
from openh4d.verify_layout import verify

HERE = Path(__file__).resolve().parent

ID_PREFIX = "SYNTH"

# What a contributor supplies that no header contains. Kept beside the code so
# it is obvious these are asserted facts about the data, not derived ones.
CLINICAL_CONTEXT = {
    "modality": "CT",
    "organ": "lung",
    "motion": "respiratory",
    "protocol": "Synthetic respiratory-gated 4D CT",
    "clinical_indication": "synthetic example, no clinical acquisition",
    "coverage": "full",
    "contrast": {"used": False, "agent": None, "phase": None},
    "ct": {"low_dose": True, "kvp": 120, "exposure_mas": 40, "recon_kernel": "synthetic"},
}

DATA_CARD = """\
---
pretty_name: "Open-H-4D -- synthetic 4D CT example"
license: cc-by-4.0
task_categories:
  - image-segmentation
tags:
  - open-h-4d
  - 4d
  - ct
  - lung
  - synthetic
language:
  - en
size_categories:
  - n<1K
---

# Open-H-4D synthetic 4D CT example

**This is not patient data.** It is a moving sphere generated by
`openh4d.synthetic_dicom`, written as DICOM and taken through the full Open-H-4D
pipeline so contributors can see the finished shape of a submission.

## Dataset Description

Two synthetic subjects of respiratory-gated 4D CT, one of whom has two studies
so the letter-suffix rule is visible. Each study holds ten time points.

## Dataset Contributor(s)

Open-H-4D tooling. Contact: openh.data+4d@gmail.com

## License / Terms of Use

CC BY 4.0. Synthetic data, no restrictions.

## Intended Usage

Checking an Open-H-4D environment, and as a worked reference for the submission
layout.

## Dataset Characterization

- **Data Collection Method:** synthetic
- **Labeling Method:** N/A
- **Acquisition system:** simulated CT geometry, 0.8 mm in plane, 1.0 mm slices

## Dataset Format

Open-H-4D submission layout: one 4D study per directory, per-time-point
`.nii.gz` volumes converted from DICOM by dcm2niix, with the original DICOM
retained under `dicom/`.

## Subject Metadata

Synthetic. No human subject information was ever present.

## Data Validation

`python -m openh4d.verify_layout <root>` reports `compliant: true`, and
`python -m openh4d.motion_report <study-dir>` shows the centre of mass tracing
a closed loop across the ten time points.

## Known Issues

Intensities are not Hounsfield units and the anatomy is a sphere. Only the
structure and the motion are meaningful.

## Ethical Considerations

None. No human subjects.
"""

CC_BY = """\
This dataset is licensed under the Creative Commons Attribution 4.0
International License (CC BY 4.0).

    https://creativecommons.org/licenses/by/4.0/

Synthetic data generated by openh4d. Contains no patient information.
"""


def apply_clinical_context(root: Path, study_ids: list[str]) -> None:
    """Fill in what the contributor knows and the headers do not.

    In a real submission the `open-h-4d-organize-dicom` skill interviews the
    contributor for exactly these fields. Here they are hard-coded, because the
    data is synthetic and we are the contributor.
    """
    for study_id in study_ids:
        path = root / study_id / "study.json"
        study = json.loads(path.read_text(encoding="utf-8"))
        study.update(CLINICAL_CONTEXT)
        study["gating"] = {
            "method": "respiratory_belt",
            "phase_source": study["gating"].get("phase_source"),
        }
        study["notes"] = "Synthetic example built by examples/synthetic-4d/build_example.py."
        path.write_text(json.dumps(study, indent=2) + "\n", encoding="utf-8")

    for ehr_dir in sorted(root.glob("*_ehr")):
        path = ehr_dir / "patient.json"
        patient = json.loads(path.read_text(encoding="utf-8"))
        patient["demographics"].update({"age_years": 61, "sex": "M"})
        patient["disease_state"]["primary_diagnosis"] = "synthetic example, no diagnosis"
        patient["disease_state"]["notes"] = ""
        patient["vitals_at_acquisition"].update(
            {
                "heart_rate_bpm": 68,
                "respiratory_rate_bpm": 15,
                "measured_relative_to_scan": "before",
            }
        )
        patient["reason_for_scan"] = {
            "category": "research_only",
            "description": "synthetic respiratory motion example",
        }
        patient["deidentification"].update(
            {
                "performed_by": "openh4d",
                "tooling": "openh4d.synthetic_dicom",
                "attestation": "Synthetic data. No human subject information was ever present.",
            }
        )
        path.write_text(json.dumps(patient, indent=2) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=HERE / "out", help="submission root to build")
    parser.add_argument("--timepoints", type=int, default=10)
    parser.add_argument(
        "--size", type=int, nargs=3, metavar=("NX", "NY", "NZ"), default=[24, 24, 12]
    )
    parser.add_argument(
        "--drop-dicom",
        action="store_true",
        help="delete the DICOM after converting, leaving only NIfTI",
    )
    parser.add_argument("--offline", action="store_true", help="never download dcm2niix")
    args = parser.parse_args(argv)

    out = Path(args.out)
    if out.exists():
        shutil.rmtree(out)
    source = out.parent / f"{out.name}-dicom-source"
    if source.exists():
        shutil.rmtree(source)

    print("1. writing a synthetic DICOM export")
    write_multi_patient_source(
        source, n_patients=2, n_timepoints=args.timepoints, shape=tuple(args.size)
    )

    print("2. checking the source is de-identified")
    phi = scan_dicom_source(source)
    if not phi.clean:
        print("source is not de-identified:", file=sys.stderr)
        for finding in phi.findings:
            print(f"  {finding.code}: {finding.message}", file=sys.stderr)
        return 1

    print("3. indexing")
    plan = build_plan(source)
    print(summarize(plan))

    print("\n4. organizing into the Open-H-4D layout")
    report = organize(
        plan,
        out,
        prefix=ID_PREFIX,
        crosswalk=out.parent / f"{out.name}-crosswalk.csv",
        submission_id="openh4d-synthetic-example",
        apply=True,
    )
    study_ids = [study["study_id"] for study in report["studies"]]
    print(f"   {report['n_patients']} patient(s), {report['n_studies']} study(ies): {study_ids}")
    print(f"   crosswalk written outside the submission: {report['crosswalk']}")

    print("5. converting DICOM to NIfTI with dcm2niix")
    for study_id in study_ids:
        result = convert_study(out / study_id, keep_dicom=not args.drop_dicom, offline=args.offline)
        print(f"   {study_id}: {result['n_timepoints']} time point(s)")

    print("6. filling in the fields only a contributor can supply")
    apply_clinical_context(out, study_ids)

    (out / "README.md").write_text(DATA_CARD, encoding="utf-8")
    (out / "LICENSE").write_text(CC_BY, encoding="utf-8")
    write_manifest(out, build_manifest(out, submission_id="openh4d-synthetic-example"))

    print("7. verifying")
    verification = verify(out)
    print(
        json.dumps({"compliant": verification.compliant, "summary": verification.summary}, indent=2)
    )
    for finding in verification.errors:
        print(f"   ERROR {finding['code']}: {finding['message']}", file=sys.stderr)
    for finding in verification.warnings:
        print(f"   warning {finding['code']}: {finding['message']}", file=sys.stderr)

    if not verification.compliant:
        return 1

    print(f"\nBuilt a compliant Open-H-4D submission at {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
