# SPDX-License-Identifier: Apache-2.0
"""Generate a small, valid Open-H-4D submission for tests and examples.

The volumes contain a sphere that moves on a closed loop across the time axis.
That matters: a generator that emitted noise or a static shape would let the
motion checks pass vacuously, and the motion checks are the part of the pipeline
unique to a 4D initiative.

Everything is tiny by default -- 24x24x12 int16 voxels, ten time points, two
patients -- so the whole generate, verify, convert chain runs in seconds and can
sit in the per-pull-request CI job.

Usage::

    python -m openh4d.synthetic --out <dir>
    python -m openh4d.synthetic --out <dir> --form dicom_phases
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np

from . import naming

DEFAULT_PREFIX = "OH4D"
DEFAULT_SHAPE = (24, 24, 12)
DEFAULT_TIMEPOINTS = 10
DEFAULT_IN_PLANE_MM = (0.8, 0.8)
DEFAULT_SLICE_SPACING_MM = 1.0

#: Two patients; the first contributed two studies, so the letter-suffix rule is
#: exercised by the default fixture rather than only by a special case.
DEFAULT_PLAN = [
    ("heart", "cardiac", 2),
    ("lung", "respiratory", 1),
]

CC_BY_NOTICE = """\
This dataset is licensed under the Creative Commons Attribution 4.0
International License (CC BY 4.0).

    https://creativecommons.org/licenses/by/4.0/

This is synthetic data generated by openh4d.synthetic for testing. It contains
no patient information of any kind.
"""


def moving_sphere(
    shape: tuple[int, int, int], n_timepoints: int, *, amplitude: float = 0.25
) -> np.ndarray:
    """A sphere translating on a closed loop, as ``(n_timepoints, *shape)`` int16.

    The loop closes so the last time point flows back into the first, the way a
    cardiac or respiratory cycle does.
    """
    nx, ny, nz = shape
    grid = np.stack(
        np.meshgrid(np.arange(nx), np.arange(ny), np.arange(nz), indexing="ij"), axis=-1
    ).astype(np.float64)

    centre = np.array([nx / 2, ny / 2, nz / 2])
    radius = min(shape) * 0.28
    travel = np.array([nx, ny, nz]) * amplitude

    volumes = np.empty((n_timepoints, *shape), dtype=np.int16)
    for index in range(n_timepoints):
        angle = 2 * np.pi * index / n_timepoints
        offset = travel * np.array([np.sin(angle), np.cos(angle), 0.0]) * 0.5
        distance = np.linalg.norm(grid - (centre + offset), axis=-1)
        # A soft edge keeps the intensity curve smooth, which is what the motion
        # report measures; a hard binary edge would quantize it.
        volumes[index] = np.clip(1000 * (1.0 - distance / radius), 0, 1000).astype(np.int16)
    return volumes


def _affine(in_plane_mm: tuple[float, float], slice_spacing_mm: float) -> np.ndarray:
    affine = np.eye(4)
    affine[0, 0] = in_plane_mm[0]
    affine[1, 1] = in_plane_mm[1]
    affine[2, 2] = slice_spacing_mm
    return affine


def _study_json(
    study_id: str,
    patient_id: str,
    organ: str,
    motion: str,
    file_layout: str,
    volumes: np.ndarray,
    in_plane_mm: tuple[float, float],
    slice_spacing_mm: float,
    *,
    derived_from_dicom: bool = False,
) -> dict[str, Any]:
    n_timepoints = int(volumes.shape[0])
    shape = tuple(int(n) for n in volumes.shape[1:])
    phase_type = "cardiac" if motion == "cardiac" else "respiratory"

    if file_layout == "single_4d":
        files = ["image4d.nii.gz"] * n_timepoints
    elif file_layout == "dicom_phases" and not derived_from_dicom:
        files = [f"dicom/t{i:04d}" for i in range(n_timepoints)]
    else:
        files = [f"t{i:04d}.nii.gz" for i in range(n_timepoints)]

    study: dict[str, Any] = {
        "schema": "open-h-4d/study/1.0",
        "study_id": study_id,
        "patient_id": patient_id,
        "modality": "CT",
        "organ": organ,
        "motion": motion,
        "protocol": f"Synthetic 4D CT ({motion} motion)",
        "clinical_indication": "synthetic test fixture",
        "file_layout": file_layout,
        "n_timepoints": n_timepoints,
        "timepoints": [
            {
                "index": i,
                "file": files[i],
                "phase_label": f"{i * 100 // n_timepoints}%",
                "phase_type": phase_type,
                "phase_fraction": round(i / n_timepoints, 4),
                "trigger_time_ms": None,
                "acquisition_time_s": None,
            }
            for i in range(n_timepoints)
        ],
        "coverage": "full",
        "coverage_notes": "",
        "contrast": {"used": False, "agent": None, "phase": None},
        "geometry": {
            "in_plane_mm": [in_plane_mm[0], in_plane_mm[1]],
            "slice_spacing_mm": slice_spacing_mm,
            "matrix": list(shape),
            "temporal_resolution_ms": 100,
            "orientation": "RAS",
        },
        "ct": {"low_dose": False, "kvp": 120, "exposure_mas": 150, "recon_kernel": "synthetic"},
        "gating": {
            "method": "retrospective_ecg" if motion == "cardiac" else "respiratory_belt",
            "phase_source": "synthetic",
        },
        "annotations": {"segmentations": [], "landmarks": [], "categorizations": []},
        "derived": [],
        "source": {
            "original_format": "synthetic",
            "converter": "openh4d.synthetic",
            "converter_args": None,
            "converted_at": None,
            "n_source_files": 0,
        },
        "waivers": [],
        "notes": "Synthetic fixture generated by openh4d.synthetic. Not real patient data.",
    }
    if derived_from_dicom:
        study["derived_from_dicom"] = True
    return study


def _patient_json(patient_id: str, study_ids: list[str], organ: str) -> dict[str, Any]:
    return {
        "schema": "open-h-4d/patient/1.0",
        "patient_id": patient_id,
        "studies": study_ids,
        "demographics": {
            "age_years": 62,
            "age_90_or_older": False,
            "sex": "F",
            "gender": None,
            "height_cm": 168,
            "weight_kg": 71.5,
            "bmi": 25.3,
            "ethnicity": None,
        },
        "disease_state": {
            "primary_diagnosis": "synthetic fixture, no diagnosis",
            "codes": [],
            "severity": None,
            "comorbidities": [],
            "notes": "",
        },
        "vitals_at_acquisition": {
            "systolic_bp_mmhg": 118,
            "diastolic_bp_mmhg": 74,
            "heart_rate_bpm": 72,
            "respiratory_rate_bpm": 14,
            "spo2_percent": 98,
            "temperature_c": None,
            "measured_relative_to_scan": "before",
        },
        "treatment_history": [],
        "reason_for_scan": {
            "category": "research_only",
            "description": f"synthetic {organ} motion fixture",
        },
        "deidentification": {
            "standard": "hipaa_safe_harbor",
            "date_shift_applied": False,
            "date_shift_offset_disclosed": False,
            "performed_by": "openh4d.synthetic",
            "tooling": "openh4d.synthetic",
            "attestation": "Synthetic data. No human subject information was ever present.",
        },
        "extra": {},
    }


def _readme(prefix: str, n_patients: int, n_studies: int) -> str:
    return f"""\
---
pretty_name: "Open-H-4D -- synthetic fixture"
license: cc-by-4.0
task_categories:
  - image-segmentation
tags:
  - open-h-4d
  - 4d
  - ct
  - synthetic
language:
  - en
size_categories:
  - n<1K
---

# Open-H-4D synthetic fixture

Generated by `python -m openh4d.synthetic`. **This is not real patient data** --
it is a moving sphere, used to exercise the Open-H-4D tooling end to end.

## Dataset Description

{n_patients} synthetic patients, {n_studies} 4D studies, identifier prefix `{prefix}`.
Each study holds ten time points of a sphere translating on a closed loop, so the
motion checks have real signal to measure rather than passing vacuously.

## Dataset Contributor(s)

Open-H-4D tooling (`openh4d.synthetic`).

## License / Terms of Use

CC BY 4.0. Synthetic data, no restrictions.

## Intended Usage

Testing the Open-H-4D organize, convert and verify pipeline, and as a worked
example of the submission layout for contributors to copy.

## Dataset Characterization

- **Data Collection Method:** synthetic
- **Labeling Method:** N/A
- **Acquisition system:** simulated CT geometry

## Dataset Format

Open-H-4D submission layout: one 4D study per directory, per-time-point
`.nii.gz` volumes, with `study.json` and `patient.json` sidecars.

## Subject Metadata

Synthetic. No human subject information was ever present.

## Known Issues

The intensity range and geometry are not physically realistic; only the
structure and the motion are.

## Ethical Considerations

None. No human subjects.
"""


def generate(
    out: Path,
    *,
    prefix: str = DEFAULT_PREFIX,
    shape: tuple[int, int, int] = DEFAULT_SHAPE,
    n_timepoints: int = DEFAULT_TIMEPOINTS,
    form: str = "timepoint_volumes",
    in_plane_mm: tuple[float, float] = DEFAULT_IN_PLANE_MM,
    slice_spacing_mm: float = DEFAULT_SLICE_SPACING_MM,
) -> Path:
    """Write a complete, verifiable synthetic submission to ``out``."""
    import nibabel as nib

    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)

    affine = _affine(in_plane_mm, slice_spacing_mm)
    n_studies = 0

    for patient_index, (organ, motion, n_patient_studies) in enumerate(DEFAULT_PLAN, start=1):
        patient_id = naming.make_patient_id(prefix, patient_index)
        study_ids = [naming.study_dir_name(patient_id, i) for i in range(1, n_patient_studies + 1)]

        for study_number, study_id in enumerate(study_ids, start=1):
            study_dir = out / study_id
            study_dir.mkdir(exist_ok=True)
            # Vary amplitude per study so two studies from one patient are not
            # byte-identical, which would hide a copy-paste bug.
            volumes = moving_sphere(shape, n_timepoints, amplitude=0.20 + 0.05 * study_number)

            if form == "single_4d":
                stacked = np.transpose(volumes, (1, 2, 3, 0))
                nib.save(nib.Nifti1Image(stacked, affine), str(study_dir / "image4d.nii.gz"))
            else:
                for index in range(n_timepoints):
                    nib.save(
                        nib.Nifti1Image(volumes[index], affine),
                        str(study_dir / f"t{index:04d}.nii.gz"),
                    )

            study = _study_json(
                study_id,
                patient_id,
                organ,
                motion,
                form,
                volumes,
                in_plane_mm,
                slice_spacing_mm,
            )
            _write_json(study_dir / "study.json", study)
            n_studies += 1

        ehr_dir = out / naming.ehr_dir_name(patient_id)
        ehr_dir.mkdir(exist_ok=True)
        _write_json(ehr_dir / "patient.json", _patient_json(patient_id, study_ids, organ))

    (out / "README.md").write_text(_readme(prefix, len(DEFAULT_PLAN), n_studies), encoding="utf-8")
    (out / "LICENSE").write_text(CC_BY_NOTICE, encoding="utf-8")

    from .manifest import build_manifest, write_manifest

    write_manifest(out, build_manifest(out, submission_id="openh4d-synthetic"))
    return out


def _write_json(path: Path, document: dict[str, Any]) -> None:
    path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")


def utc_now() -> str:
    """Timestamp used by generated sidecars, so output is uniform."""
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, required=True, help="output directory")
    parser.add_argument("--prefix", default=DEFAULT_PREFIX, help="patient identifier prefix")
    parser.add_argument(
        "--timepoints", type=int, default=DEFAULT_TIMEPOINTS, help="time points per study"
    )
    parser.add_argument(
        "--form",
        choices=["timepoint_volumes", "single_4d"],
        default="timepoint_volumes",
        help="image form to emit (the DICOM form is produced by synthetic_dicom)",
    )
    parser.add_argument(
        "--size",
        type=int,
        nargs=3,
        metavar=("NX", "NY", "NZ"),
        default=list(DEFAULT_SHAPE),
        help="volume dimensions",
    )
    args = parser.parse_args(argv)

    out = generate(
        args.out,
        prefix=args.prefix,
        shape=tuple(args.size),  # type: ignore[arg-type]
        n_timepoints=args.timepoints,
        form=args.form,
    )
    print(f"wrote synthetic submission to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
